apiVersion: v1
kind: Service
metadata:
  name: angular
spec:
  selector:
    app: angular
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular
  labels:
    app: angular
spec:
  replicas: 3      
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      hostname: angular
      containers:
      - name: angular
        image: vikhilp98/angular
        ports:
        - containerPort: 8081
