apiVersion: v1
kind: Service
metadata:
  name: rest
spec:
  selector:
    app: rest
  ports:
  - protocol: TCP
    port: 9966
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest
  labels:
    app: rest
spec:
  replicas: 3      
  selector:
    matchLabels:
      app: rest
  template:
    metadata:
      labels:
        app: rest
    spec:
      hostname: rest
      containers:
      - name: rest
        image: vikhilp98/rest
        ports:
        - containerPort: 9966
